# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  helm: circleci/helm@0.2.3

executors:
  default:
    docker:
      # specify the version
      - image: circleci/golang:1.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /home/circleci/project
    environment:
      GOPATH: /home/circleci/go

commands:
  setup:
    steps:
    - helm/install-helm-client:
        version: v3.2.2
    - run: mkdir -p /home/circleci/project && cd /home/circleci/project
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
        - go-cache-v1-{{ arch }}-{{ checksum "go.sum" }}
  docker_login:
    steps:
    - run: docker login --username="$DOCKER_USER" --password="$DOCKER_PASSWORD"
  build_image:
    parameters:
      tag:
        type: string
    steps:
    - run: docker build --progress=plain --tag=docker.io/vladlosev/node-relabeler:<<parameters.tag>> .
  push_image:
    parameters:
      tag:
        type: string
    steps:
    - run: docker push docker.io/vladlosev/node-relabeler:<<parameters.tag>>

jobs:
  build_test:
    executor: default
    steps:
      - setup
      - run: go test -v ./...
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o node-relabeler
      - run: helm lint charts/node-relabeler
      - build_image:
          tag: $CIRCLE_SHA1
      - save_cache:
          key: go-cache-v1-{{ arch }}-{{ checksum "go.sum" }}
          paths:
          - /home/circleci/go
  push_master_image:
    executor: default
    steps:
      - setup
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o node-relabeler
      - build_image:
          tag: master-$CIRCLE_SHA1
      - docker_login
      - push_image:
          tag: master-$CIRCLE_SHA1
      - save_cache:
          key: go-cache-v1-{{ arch }}-{{ checksum "go.sum" }}
          paths:
          - /home/circleci/go
  push_release_image:
    executor: default
    steps:
      - setup
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o node-relabeler
      - build_image:
          tag: $CIRCLE_TAG
      - docker_login
      - push_image:
          tag: $CIRCLE_TAG

workflows:
  build_and_deploy:
    jobs:
    - build_test:
        filters:
          tags:
            only: /.*/
    - push_master_image:
        context: docker_hub
        requires:
        - build_test
        filters:
          branches:
            only: master
    - push_release_image:
        context: docker_hub
        requires:
        - build_test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-[a-z0-9]+)?/
